//This query shows if any new watchlists created
Watchlist 
| summarize arg_max(TimeGenerated, *) by WatchlistId // take the last operation performed on a watchlist
| extend Creator=CreatedBy.email 
| where Creator contains "<migration query>" // Give person's e-mail who is migrating. 
| extend Lastupdatedby=UpdatedBy.email 
| project TimeGenerated,WatchlistId, WatchlistAlias, Creator, Type, Lastupdatedby
