//Database Authentication Failed
let timeframe=90d; 
AzureDiagnostics 
| where TimeGenerated> ago(timeframe) 
| where Category contains "SQLSecurityAuditEvents" 
| where action_name_s contains "DATABASE AUTHENTICATION FAILED" 
| extend Additional=parse_xml(additional_information_s) 
| project TimeGenerated, event_time_t,ClientComputer=host_name_s, Action=action_name_s, action_id_s, ClientApp=application_name_s,User=server_principal_name_s,ClientIP=client_ip_s, Server=LogicalServerName_s, error_code=Additional.login_information.error_code,error_state=Additional.login_information.error_state, database_name_s, statement_s, connection_id_g, succeeded_s
