let timeframe=24h; 
AzureDiagnostics 
| where TimeGenerated> ago(timeframe) 
| where Category contains "SQLSecurityAuditEvents" 
| where statement_s contains "DROP TABLE" 
| parse kind=regex flags=i statement_s with * "DROP TABLE \\[" DeletedTable "\\]" * 
| where succeeded_s contains "true" 
| where isnotempty(DeletedTable) 
| project TimeGenerated, event_time_t, DatabaseName=database_name_s,object_name_s, ClientApp=application_name_s, ClientIP=client_ip_s, ClientComputer=host_name_s, SubjectUser=server_principal_name_s, TargetServer=server_instance_name_s,Action=action_name_s, DeletedTable, connection_id_g, statement_s
